### ISSUE TITLE
Corvette - Whale Shaped

### ISSUE THREAD

**Issue by Alkaliii** [tsunamayo/Skywanderers-Pathfinder-Group-Build#3]
![Skywanderers 2020-01-29 10_43_46 PM](https://user-images.githubusercontent.com/53021785/73423305-f5171d00-42e8-11ea-9fcd-afdfac5bec52.png)

Some minor changes and stuff added turrets to the top and bottom and did some exterior stuff
[OOO-EX48 (2).zip](https://github.com/tsunamayo/Skywanderers-Pathfinder-Group-Build/files/4132418/OOO-EX48.2.zip)

### Version Two
Read the post on factions currently working to create elements that can be consistent between my builds. re-did the front of the craft 
![Skywanderers 2020-01-28 7_45_07 PM](https://user-images.githubusercontent.com/53021785/73324057-e2c4b280-4206-11ea-88aa-7cba2262d7da.png)
...
### Version One
![Skywanderers 2020-01-25 1_03_02 PM](https://user-images.githubusercontent.com/53021785/73126709-299a7a00-3f73-11ea-9af4-d6030e0a32fe.png)
![Skywanderers 2020-01-25 1_02_30 PM](https://user-images.githubusercontent.com/53021785/73126710-299a7a00-3f73-11ea-9caf-4bccf560550c.png)

Work in progress on a 50m medium-size ship. Working on a generic whale shark shape that's nothing too fancy, any feedback helps thanks.

[OOO-EX48.zip](https://github.com/tsunamayo/Skywanderers-Pathfinder-Group-Build/files/4112689/OOO-EX48.zip)

**Comment by tsunamayo** [comment]
Hi! Thanks for posting your ship! I had a look at, and while I like the feel I am not 100% it would fit into the game, given the whale nature of it. I like the asymmetry though.
Is it supposed to be civilian?
Cheers!

**Comment by Alkaliii** [comment]
Yea I might go with a civilian ship not sure yet, I'll finish some more stuff up and update the blueprint or maybe change the faction style
